### ISSUE TITLE
Fix error when evaluating the model

### ISSUE THREAD

**Issue by rissalhedna** [ZHCSJ666/ML-24-25#10]
I get the error below when running the file eval.py. (training was successful)

**Comment by rissalhedna** [comment]
<img width="1071" alt="Screenshot 2024-11-17 at 12 11 34" src="https://github.com/user-attachments/assets/55263070-a0ed-4a01-beb8-8ed7f111a523">

**Comment by ndersam** [comment]
Don't know if you've solved it but out have to pass path to trained checkpoint (.ckpt file) to evaluate.
```bash
python eval.py model=simple-transformer data=commit_chronicle ckpt_path=/path/to/model.ckpt
```
